question_data = [
    {"type": "multiple", "difficulty": "hard", "category": "Entertainment: Music",
     "question": "Who was not in the band &quot;The Smiths&quot;?", "correct_answer": "Martin Chambers",
     "incorrect_answers": ["Morrissey", "Andy Rourke", "Mike Joyce"]},
    {"type": "multiple", "difficulty": "easy", "category": "General Knowledge",
     "question": "What is the largest organ of the human body?", "correct_answer": "Skin",
     "incorrect_answers": ["Heart", "large Intestine", "Liver"]},
    {"type": "multiple", "difficulty": "medium", "category": "Science: Computers",
     "question": "Which coding language was the #1 programming language in terms of usage on GitHub in 2015?",
     "correct_answer": "JavaScript", "incorrect_answers": ["C#", "Python", "PHP"]},
    {"type": "boolean", "difficulty": "medium", "category": "Vehicles",
     "question": "The Japanese Shinkansen beat the French TGV&#039;s speed record for fastest electric rail train.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "multiple", "difficulty": "hard", "category": "History",
     "question": "Which of these positions did the astronomer and physicist Isaac Newton not hold?",
     "correct_answer": "Surveyor to the City of London",
     "incorrect_answers": ["Professor of Mathematics", "Warden of the Royal Mint", "Member of Parliament"]},
    {"type": "multiple", "difficulty": "medium", "category": "History",
     "question": "John Moses Browning, the designer of the M1918 BAR (Browning Automatic Rifle) was a part of which religion?",
     "correct_answer": "Mormon", "incorrect_answers": ["Catholic", "Jewish", "Atheist"]},
    {"type": "multiple", "difficulty": "medium", "category": "Geography",
     "question": "In which English county is Stonehenge?", "correct_answer": "Wiltshire",
     "incorrect_answers": ["Somerset", "Cumbria", "Herefordshire"]},
    {"type": "boolean", "difficulty": "medium", "category": "Vehicles",
     "question": "The majority of Subaru vehicles are made in China.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "multiple", "difficulty": "medium", "category": "Entertainment: Film",
                                      "question": "In the Mad Max franchise, what type of car is the Pursuit Special driven by Max?",
                                      "correct_answer": "Ford Falcon",
                                      "incorrect_answers": ["Holden Monaro", "Chrysler Valiant Charger",
                                                            "Pontiac Firebird"]},
    {"type": "multiple", "difficulty": "hard", "category": "General Knowledge",
     "question": "Which musician has collaborated with American producer Porter Robinson and released the 2016 song &quot;Shelter&quot;?",
     "correct_answer": "Madeon", "incorrect_answers": ["Mat Zo", "deadmau5", "Zedd"]}]

